this.gbar_=this.gbar_||{};(function(_){var window=this;
try{
_.ae=function(a,b,c){if(!a.j)if(c instanceof Array)for(var d of c)_.ae(a,b,d);else{d=(0,_.z)(a.A,a,b);const e=a.s+c;a.s++;b.setAttribute("data-eqid",e);a.B[e]=d;b&&b.addEventListener?b.addEventListener(c,d,!1):b&&b.attachEvent?b.attachEvent("on"+c,d):a.o.log(Error("w`"+b))}};
}catch(e){_._DumpException(e)}
try{
_.be=function(){if(!_.m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{_.m.addEventListener("test",()=>{},b),_.m.removeEventListener("test",()=>{},b)}catch(c){}return a}();
}catch(e){_._DumpException(e)}
try{
var ce=document.querySelector(".gb_Q .gb_e"),de=document.querySelector("#gb.gb_Tc");ce&&!de&&_.ae(_.Qd,ce,"click");
}catch(e){_._DumpException(e)}
try{
_.ee=function(a,b){return 0<=_.wb(a,b)};_.fe=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};_.ge=function(a,b){this.width=a;this.height=b};_.l=_.ge.prototype;_.l.aspectRatio=function(){return this.width/this.height};_.l.Hb=function(){return!(this.width*this.height)};_.l.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};_.l.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.l.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.he=function(a,b){return(b||document).getElementsByTagName(String(a))};_.je=function(a){return _.ie(document,a)};_.ie=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};_.ke=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.le=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
}catch(e){_._DumpException(e)}
try{
_.me=function(a){return _.nb(a)&&1==a.nodeType};_.ne=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else _.ke(a),a.appendChild(_.le(a).createTextNode(String(b)))};var oe;_.pe=function(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")};_.qe=function(a,b,c){Array.isArray(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(oe||(oe={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=oe,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)};var re,se,te;re=function(a){return"string"==typeof a.className?a.className:a.getAttribute&&a.getAttribute("class")||""};se=function(a){return a.classList?a.classList:re(a).match(/\S+/g)||[]};te=function(a,b){"string"==typeof a.className?a.className=b:a.setAttribute&&a.setAttribute("class",b)};_.P=function(a,b){return a.classList?a.classList.contains(b):_.ee(se(a),b)};_.Q=function(a,b){if(a.classList)a.classList.add(b);else if(!_.P(a,b)){var c=re(a);te(a,c+(0<c.length?" "+b:b))}};
_.ue=function(a,b){if(a.classList)Array.prototype.forEach.call(b,function(e){_.Q(a,e)});else{var c={};Array.prototype.forEach.call(se(a),function(e){c[e]=!0});Array.prototype.forEach.call(b,function(e){c[e]=!0});b="";for(var d in c)b+=0<b.length?" "+d:d;te(a,b)}};_.ve=function(a,b){a.classList?a.classList.remove(b):_.P(a,b)&&te(a,Array.prototype.filter.call(se(a),function(c){return c!=b}).join(" "))};
_.we=function(a,b){a.classList?Array.prototype.forEach.call(b,function(c){_.ve(a,c)}):te(a,Array.prototype.filter.call(se(a),function(c){return!_.ee(b,c)}).join(" "))};var Ae;_.ze=function(a,b,c,d,e,f){if(_.Eb&&e)return _.xe(a);if(e&&!d)return!1;if(!_.Cb){"number"===typeof b&&(b=_.ye(b));var g=17==b||18==b||_.Eb&&91==b;if((!c||_.Eb)&&g||_.Eb&&16==b&&(d||f))return!1}if((_.Db||_.Ab)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(_.D&&d&&b==a)return!1;switch(a){case 13:return _.Cb?f||e?!1:!(c&&d):!0;case 27:return!(_.Db||_.Ab||_.Cb)}return _.Cb&&(d||e||f)?!1:_.xe(a)};
_.xe=function(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||(_.Db||_.Ab)&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:case 163:case 58:return!0;case 173:return _.Cb;default:return!1}};_.ye=function(a){if(_.Cb)a=Ae(a);else if(_.Eb&&_.Db)switch(a){case 93:a=91}return a};
Ae=function(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};
}catch(e){_._DumpException(e)}
try{
var De;_.Be=function(a,b){if(void 0!==a.i||void 0!==a.j)throw Error("B");a.j=b;_.Hd(a)};_.Ce=class extends _.M{constructor(a){super(a)}};De=0;_.Ee=function(a){return Object.prototype.hasOwnProperty.call(a,_.ob)&&a[_.ob]||(a[_.ob]=++De)};_.Fe=function(a){return _.rd(_.nd.i(),a)};
}catch(e){_._DumpException(e)}
try{
var Ie;_.Ge=function(a,b){b=_.wb(a,b);let c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c};_.He=function(a,b,c){for(const d in a)b.call(c,a[d],d,a)};Ie=function(a,b){for(const c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};_.Je=function(a,b){try{return _.yb(a[b]),!0}catch(c){}return!1};_.Le=function(a,b){this.type="function"==typeof _.Ke&&a instanceof _.Ke?String(a):a;this.currentTarget=this.target=b;this.defaultPrevented=this.i=!1};_.Le.prototype.stopPropagation=function(){this.i=!0};_.Le.prototype.preventDefault=function(){this.defaultPrevented=!0};_.Oe=function(a,b){_.Le.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.Qa=null;a&&this.init(a,b)};_.C(_.Oe,_.Le);var Pe={2:"touch",3:"pen",4:"mouse"};
_.Oe.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;(b=a.relatedTarget)?_.Cb&&(_.Je(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.offsetX=_.Db||void 0!==
a.offsetX?a.offsetX:a.layerX,this.offsetY=_.Db||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===
typeof a.pointerType?a.pointerType:Pe[a.pointerType]||"";this.state=a.state;this.Qa=a;a.defaultPrevented&&_.Oe.V.preventDefault.call(this)};_.Oe.prototype.stopPropagation=function(){_.Oe.V.stopPropagation.call(this);this.Qa.stopPropagation?this.Qa.stopPropagation():this.Qa.cancelBubble=!0};_.Oe.prototype.preventDefault=function(){_.Oe.V.preventDefault.call(this);var a=this.Qa;a.preventDefault?a.preventDefault():a.returnValue=!1};_.Qe="closure_listenable_"+(1E6*Math.random()|0);_.Re=function(a){return!(!a||!a[_.Qe])};var Se=0;var Te;Te=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Cd=e;this.key=++Se;this.qd=this.ud=!1};_.Ue=function(a){a.qd=!0;a.listener=null;a.proxy=null;a.src=null;a.Cd=null};_.Ve=function(a){this.src=a;this.i={};this.j=0};_.Ve.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.i[f];a||(a=this.i[f]=[],this.j++);var g=We(a,b,d,e);-1<g?(b=a[g],c||(b.ud=!1)):(b=new Te(b,this.src,f,!!d,e),b.ud=c,a.push(b));return b};_.Ve.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.i))return!1;var e=this.i[a];b=We(e,b,c,d);return-1<b?(_.Ue(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.i[a],this.j--),!0):!1};
_.Xe=function(a,b){var c=b.type;if(!(c in a.i))return!1;var d=_.Ge(a.i[c],b);d&&(_.Ue(b),0==a.i[c].length&&(delete a.i[c],a.j--));return d};_.Ve.prototype.Ad=function(a,b){a=this.i[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};_.Ve.prototype.Vc=function(a,b,c,d){a=this.i[a.toString()];var e=-1;a&&(e=We(a,b,c,d));return-1<e?a[e]:null};
_.Ve.prototype.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Ie(this.i,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&f[g].capture!=b))return!0;return!1})};var We=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.qd&&f.listener==b&&f.capture==!!c&&f.Cd==d)return e}return-1};var Ye,Ze,$e,cf,ef,ff,gf,kf;Ye="closure_lm_"+(1E6*Math.random()|0);Ze={};$e=0;_.R=function(a,b,c,d,e){if(d&&d.once)return _.af(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)_.R(a,b[f],c,d,e);return null}c=_.bf(c);return _.Re(a)?a.listen(b,c,_.nb(d)?!!d.capture:!!d,e):cf(a,b,c,!1,d,e)};
cf=function(a,b,c,d,e,f){if(!b)throw Error("C");var g=_.nb(e)?!!e.capture:!!e,h=_.df(a);h||(a[Ye]=h=new _.Ve(a));c=h.add(b,c,d,g,f);if(c.proxy)return c;d=ef();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)_.be||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(ff(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("D");$e++;return c};
ef=function(){const a=gf,b=function(c){return a.call(b.src,b.listener,c)};return b};_.af=function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)_.af(a,b[f],c,d,e);return null}c=_.bf(c);return _.Re(a)?a.Ha(b,c,_.nb(d)?!!d.capture:!!d,e):cf(a,b,c,!0,d,e)};_.hf=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)_.hf(a,b[f],c,d,e);else d=_.nb(d)?!!d.capture:!!d,c=_.bf(c),_.Re(a)?a.Da(b,c,d,e):a&&(a=_.df(a))&&(b=a.Vc(b,c,d,e))&&_.jf(b)};
_.jf=function(a){if("number"===typeof a||!a||a.qd)return!1;var b=a.src;if(_.Re(b))return b.xe(a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(ff(c),d):b.addListener&&b.removeListener&&b.removeListener(d);$e--;(c=_.df(b))?(_.Xe(c,a),0==c.j&&(c.src=null,b[Ye]=null)):_.Ue(a);return!0};ff=function(a){return a in Ze?Ze[a]:Ze[a]="on"+a};
gf=function(a,b){if(a.qd)a=!0;else{b=new _.Oe(b,this);var c=a.listener,d=a.Cd||a.src;a.ud&&_.jf(a);a=c.call(d,b)}return a};_.df=function(a){a=a[Ye];return a instanceof _.Ve?a:null};kf="__closure_events_fn_"+(1E9*Math.random()>>>0);_.bf=function(a){if("function"===typeof a)return a;a[kf]||(a[kf]=function(b){return a.handleEvent(b)});return a[kf]};
}catch(e){_._DumpException(e)}
try{
var mf,sf,uf,xf,zf,Ef,If;_.lf=function(a){a&&"function"==typeof a.na&&a.na()};mf=function(a){_.m.setTimeout(()=>{throw a;},0)};_.nf=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"};_.of=function(a){var b=_.nf(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.pf=function(a,b,c){return void 0!==_.fc(a,b,c,!1)};_.qf=function(a,b){b=_.fe(_.lf,b);a.Ga?b():(a.ta||(a.ta=[]),a.ta.push(b))};
_.rf=function(a){var b=0,c;for(c in a.i){for(var d=a.i[c],e=0;e<d.length;e++)++b,_.Ue(d[e]);delete a.i[c];a.j--}};_.tf=function(a){return/^[\s\xa0]*$/.test(a)};uf=function(a,b){return a<b?-1:a>b?1:0};
_.vf=function(a,b){let c=0;a=(0,_.tb)(String(a)).split(".");b=(0,_.tb)(String(b)).split(".");const d=Math.max(a.length,b.length);for(let g=0;0==c&&g<d;g++){var e=a[g]||"",f=b[g]||"";do{e=/(\d*)(\D*)(.*)/.exec(e)||["","","",""];f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];if(0==e[0].length&&0==f[0].length)break;c=uf(0==e[1].length?0:parseInt(e[1],10),0==f[1].length?0:parseInt(f[1],10))||uf(0==e[2].length,0==f[2].length)||uf(e[2],f[2]);e=e[3];f=f[3]}while(0==c)}return c};
_.wf=function(a,b){return Array.prototype.some.call(a,b,void 0)};xf=function(){};_.yf=function(a,b){return"string"===typeof b?a.getElementById(b):b};zf={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.Af=function(a,b){_.He(b,function(c,d){c&&"object"==typeof c&&c.Ab&&(c=c.hb());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:zf.hasOwnProperty(d)?a.setAttribute(zf[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})};_.Bf=function(a){return"CSS1Compat"==a.compatMode};_.Cf=function(a){a=a.document;a=_.Bf(a)?a.documentElement:a.body;return new _.ge(a.clientWidth,a.clientHeight)};
_.Df=function(a){return a?a.parentWindow||a.defaultView:window};Ef=function(a,b,c){function d(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(var e=2;e<c.length;e++){var f=c[e];if(!_.of(f)||_.nb(f)&&0<f.nodeType)d(f);else{a:{if(f&&"number"==typeof f.length){if(_.nb(f)){var g="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){g="function"==typeof f.item;break a}}g=!1}_.xb(g?_.xa(f):f,d)}}};
_.Ff=function(a,b){var c=b[1],d=_.ie(a,String(b[0]));c&&("string"===typeof c?d.className=c:Array.isArray(c)?d.className=c.join(" "):_.Af(d,c));2<b.length&&Ef(a,d,b);return d};_.Gf=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};_.Hf=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
If=function(a){this.i=a||_.m.document||document};_.l=If.prototype;_.l.D=function(a){return _.yf(this.i,a)};_.l.ob=function(a,b,c){return _.Ff(this.i,arguments)};_.l.appendChild=function(a,b){a.appendChild(b)};_.l.ye=_.ke;_.l.Cf=_.Gf;_.l.Bf=_.Hf;_.Jf=function(a){return a?new If(_.le(a)):sf||(sf=new If)};_.S=function(){_.N.call(this);this.ab=new _.Ve(this);this.Nf=this;this.od=null};_.C(_.S,_.N);_.S.prototype[_.Qe]=!0;_.l=_.S.prototype;_.l.fg=function(){return this.od};_.l.Ac=function(a){this.od=a};
_.l.addEventListener=function(a,b,c,d){_.R(this,a,b,c,d)};_.l.removeEventListener=function(a,b,c,d){_.hf(this,a,b,c,d)};
_.l.dispatchEvent=function(a){var b,c=this.od;if(c)for(b=[];c;c=c.od)b.push(c);c=this.Nf;var d=a.type||a;if("string"===typeof a)a=new _.Le(a,c);else if(a instanceof _.Le)a.target=a.target||c;else{var e=a;a=new _.Le(d,c);_.jb(a,e)}e=!0;if(b)for(var f=b.length-1;!a.i&&0<=f;f--){var g=a.currentTarget=b[f];e=Kf(g,d,!0,a)&&e}a.i||(g=a.currentTarget=c,e=Kf(g,d,!0,a)&&e,a.i||(e=Kf(g,d,!1,a)&&e));if(b)for(f=0;!a.i&&f<b.length;f++)g=a.currentTarget=b[f],e=Kf(g,d,!1,a)&&e;return e};
_.l.N=function(){_.S.V.N.call(this);this.ab&&_.rf(this.ab);this.od=null};_.l.listen=function(a,b,c,d){return this.ab.add(String(a),b,!1,c,d)};_.l.Ha=function(a,b,c,d){return this.ab.add(String(a),b,!0,c,d)};_.l.Da=function(a,b,c,d){this.ab.remove(String(a),b,c,d)};_.l.xe=function(a){return _.Xe(this.ab,a)};
var Kf=function(a,b,c,d){b=a.ab.i[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.qd&&g.capture==c){var h=g.listener,k=g.Cd||g.src;g.ud&&a.xe(g);e=!1!==h.call(k,d)&&e}}return e&&!d.defaultPrevented};_.S.prototype.Ad=function(a,b){return this.ab.Ad(String(a),b)};_.S.prototype.Vc=function(a,b,c,d){return this.ab.Vc(String(a),b,c,d)};_.S.prototype.hasListener=function(a,b){return this.ab.hasListener(void 0!==a?String(a):void 0,b)};var Lf=function(a,b){a.s(b);100>a.j&&(a.j++,b.next=a.i,a.i=b)},Mf=class{constructor(a,b){this.o=a;this.s=b;this.j=0;this.i=null}get(){let a;0<this.j?(this.j--,a=this.i,this.i=a.next,a.next=null):a=this.o();return a}};var Nf,Of=function(){var a=_.m.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.n("Presto")&&(a=function(){var e=_.je("IFRAME");e.style.display="none";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.close();var g="callImmediate"+Math.random(),h="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=(0,_.z)(function(k){if(("*"==h||k.origin==h)&&k.data==g)this.port1.onmessage()},
this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,h)}}});if("undefined"!==typeof a&&!_.ja()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.Ge;c.Ge=null;e()}};return function(e){d.next={Ge:e};d=d.next;b.port2.postMessage(0)}}return function(e){_.m.setTimeout(e,0)}};var Qf=class{constructor(){this.j=this.i=null}add(a,b){const c=Pf.get();c.set(a,b);this.j?this.j.next=c:this.i=c;this.j=c}remove(){let a=null;this.i&&(a=this.i,this.i=this.i.next,this.i||(this.j=null),a.next=null);return a}},Pf=new Mf(()=>new Rf,a=>a.reset()),Rf=class{constructor(){this.next=this.scope=this.i=null}set(a,b){this.i=a;this.scope=b;this.next=null}reset(){this.next=this.scope=this.i=null}};var Sf,Tf=!1,Uf=new Qf,Wf=(a,b)=>{Sf||Vf();Tf||(Sf(),Tf=!0);Uf.add(a,b)},Vf=()=>{if(_.m.Promise&&_.m.Promise.resolve){const a=_.m.Promise.resolve(void 0);Sf=()=>{a.then(Xf)}}else Sf=()=>{var a=Xf;"function"!==typeof _.m.setImmediate||_.m.Window&&_.m.Window.prototype&&!_.ka()&&_.m.Window.prototype.setImmediate==_.m.setImmediate?(Nf||(Nf=Of()),Nf(a)):_.m.setImmediate(a)}},Xf=()=>{let a;for(;a=Uf.remove();){try{a.i.call(a.scope)}catch(b){mf(b)}Lf(Pf,a)}Tf=!1};_.Yf=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var ag,hg,mg,lg,ng;_.$f=function(a){this.i=0;this.C=void 0;this.s=this.j=this.o=null;this.v=this.B=!1;if(a!=xf)try{var b=this;a.call(void 0,function(c){Zf(b,2,c)},function(c){Zf(b,3,c)})}catch(c){Zf(this,3,c)}};ag=function(){this.next=this.o=this.j=this.s=this.i=null;this.v=!1};ag.prototype.reset=function(){this.o=this.j=this.s=this.i=null;this.v=!1};var bg=new Mf(function(){return new ag},function(a){a.reset()}),cg=function(a,b,c){var d=bg.get();d.s=a;d.j=b;d.o=c;return d};
_.$f.prototype.then=function(a,b,c){return dg(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};_.$f.prototype.$goog_Thenable=!0;_.$f.prototype.A=function(a,b){return dg(this,null,a,b)};_.$f.prototype.catch=_.$f.prototype.A;_.$f.prototype.cancel=function(a){if(0==this.i){var b=new _.eg(a);Wf(function(){fg(this,b)},this)}};
var fg=function(a,b){if(0==a.i)if(a.o){var c=a.o;if(c.j){for(var d=0,e=null,f=null,g=c.j;g&&(g.v||(d++,g.i==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.i&&1==d?fg(c,b):(f?(d=f,d.next==c.s&&(c.s=d),d.next=d.next.next):gg(c),hg(c,e,3,b)))}a.o=null}else Zf(a,3,b)},jg=function(a,b){a.j||2!=a.i&&3!=a.i||ig(a);a.s?a.s.next=b:a.j=b;a.s=b},dg=function(a,b,c,d){var e=cg(null,null,null);e.i=new _.$f(function(f,g){e.s=b?function(h){try{var k=b.call(d,h);f(k)}catch(p){g(p)}}:f;e.j=c?function(h){try{var k=
c.call(d,h);void 0===k&&h instanceof _.eg?g(h):f(k)}catch(p){g(p)}}:g});e.i.o=a;jg(a,e);return e.i};_.$f.prototype.G=function(a){this.i=0;Zf(this,2,a)};_.$f.prototype.H=function(a){this.i=0;Zf(this,3,a)};
var Zf=function(a,b,c){if(0==a.i){a===c&&(b=3,c=new TypeError("E"));a.i=1;a:{var d=c,e=a.G,f=a.H;if(d instanceof _.$f){jg(d,cg(e||xf,f||null,a));var g=!0}else if(_.Yf(d))d.then(e,f,a),g=!0;else{if(_.nb(d))try{var h=d.then;if("function"===typeof h){kg(d,h,e,f,a);g=!0;break a}}catch(k){f.call(a,k);g=!0;break a}g=!1}}g||(a.C=c,a.i=b,a.o=null,ig(a),3!=b||c instanceof _.eg||lg(a,c))}},kg=function(a,b,c,d,e){var f=!1,g=function(k){f||(f=!0,c.call(e,k))},h=function(k){f||(f=!0,d.call(e,k))};try{b.call(a,
g,h)}catch(k){h(k)}},ig=function(a){a.B||(a.B=!0,Wf(a.F,a))},gg=function(a){var b=null;a.j&&(b=a.j,a.j=b.next,b.next=null);a.j||(a.s=null);return b};_.$f.prototype.F=function(){for(var a;a=gg(this);)hg(this,a,this.i,this.C);this.B=!1};hg=function(a,b,c,d){if(3==c&&b.j&&!b.v)for(;a&&a.v;a=a.o)a.v=!1;if(b.i)b.i.o=null,mg(b,c,d);else try{b.v?b.s.call(b.o):mg(b,c,d)}catch(e){ng.call(null,e)}Lf(bg,b)};mg=function(a,b,c){2==b?a.s.call(a.o,c):a.j&&a.j.call(a.o,c)};
lg=function(a,b){a.v=!0;Wf(function(){a.v&&ng.call(null,b)})};ng=mf;_.eg=function(a){_.aa.call(this,a)};_.C(_.eg,_.aa);_.eg.prototype.name="cancel";_.og=function(a,b){_.S.call(this);this.j=a||1;this.i=b||_.m;this.o=(0,_.z)(this.Hg,this);this.s=Date.now()};_.C(_.og,_.S);_.l=_.og.prototype;_.l.Eb=!1;_.l.qb=null;_.l.Hg=function(){if(this.Eb){var a=Date.now()-this.s;0<a&&a<.8*this.j?this.qb=this.i.setTimeout(this.o,this.j-a):(this.qb&&(this.i.clearTimeout(this.qb),this.qb=null),this.dispatchEvent("tick"),this.Eb&&(this.stop(),this.start()))}};_.l.start=function(){this.Eb=!0;this.qb||(this.qb=this.i.setTimeout(this.o,this.j),this.s=Date.now())};
_.l.stop=function(){this.Eb=!1;this.qb&&(this.i.clearTimeout(this.qb),this.qb=null)};_.l.N=function(){_.og.V.N.call(this);this.stop();delete this.i};_.pg=function(a,b,c){if("function"===typeof a)c&&(a=(0,_.z)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.z)(a.handleEvent,a);else throw Error("F");return 2147483647<Number(b)?-1:_.m.setTimeout(a,b||0)};_.qg=function(a){_.m.clearTimeout(a)};
}catch(e){_._DumpException(e)}
try{
_.rg=function(a,b,c){return Array.prototype.filter.call(a,b,c)};_.sg=function(a){_.N.call(this);this.L=a;this.J={}};_.C(_.sg,_.N);var tg=[];_.sg.prototype.listen=function(a,b,c,d){return ug(this,a,b,c,d)};_.sg.prototype.s=function(a,b,c,d,e){return ug(this,a,b,c,d,e)};var ug=function(a,b,c,d,e,f){Array.isArray(c)||(c&&(tg[0]=c.toString()),c=tg);for(var g=0;g<c.length;g++){var h=_.R(b,c[g],d||a.handleEvent,e||!1,f||a.L||a);if(!h)break;a.J[h.key]=h}return a};
_.sg.prototype.Ha=function(a,b,c,d){return vg(this,a,b,c,d)};var vg=function(a,b,c,d,e,f){if(Array.isArray(c))for(var g=0;g<c.length;g++)vg(a,b,c[g],d,e,f);else{b=_.af(b,c,d||a.handleEvent,e,f||a.L||a);if(!b)return a;a.J[b.key]=b}return a};
_.sg.prototype.Da=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.Da(a,b[f],c,d,e);else c=c||this.handleEvent,d=_.nb(d)?!!d.capture:!!d,e=e||this.L||this,c=_.bf(c),d=!!d,b=_.Re(a)?a.Vc(b,c,d,e):a?(a=_.df(a))?a.Vc(b,c,d,e):null:null,b&&(_.jf(b),delete this.J[b.key])};_.wg=function(a){_.He(a.J,function(b,c){this.J.hasOwnProperty(c)&&_.jf(b)},a);a.J={}};_.sg.prototype.N=function(){_.sg.V.N.call(this);_.wg(this)};_.sg.prototype.handleEvent=function(){throw Error("G");};
}catch(e){_._DumpException(e)}
try{
_.xg=function(a){return new _.ge(a.width,a.height)};_.yg=function(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};_.zg=function(a){return a.replace(RegExp("(^|[\\s]+)([a-z])","g"),function(b,c,d){return c+d.toUpperCase()})};_.Ag=function(a,b){return a==b?!0:a&&b?a.width==b.width&&a.height==b.height:!1};_.Bg=function(){return _.Db?"Webkit":_.Cb?"Moz":_.D?"ms":null};var Eg;_.T=function(a,b,c){if("string"===typeof b)(b=_.Dg(a,b))&&(a.style[b]=c);else for(var d in b){c=a;var e=b[d],f=_.Dg(c,d);f&&(c.style[f]=e)}};Eg={};_.Dg=function(a,b){var c=Eg[b];if(!c){var d=_.yg(b);c=d;void 0===a.style[d]&&(d=_.Bg()+_.zg(d),void 0!==a.style[d]&&(c=d));Eg[b]=c}return c};_.Fg=function(a,b){var c=_.le(a);return c.defaultView&&c.defaultView.getComputedStyle&&(a=c.defaultView.getComputedStyle(a,null))?a[b]||a.getPropertyValue(b)||"":""};
_.Gg=function(a,b){return _.Fg(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]};_.Hg=function(a){try{return a.getBoundingClientRect()}catch(b){return{left:0,top:0,right:0,bottom:0}}};_.Jg=function(a){var b=_.Ig;if("none"!=_.Gg(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a};
_.Ig=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=_.Db&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=_.Hg(a),new _.ge(a.right-a.left,a.bottom-a.top)):new _.ge(b,c)};_.Kg=function(a,b){a.style.display=b?"":"none"};_.Lg=_.Cb?"MozUserSelect":_.Db||_.Ab?"WebkitUserSelect":null;
}catch(e){_._DumpException(e)}
try{
var Mg,Og;Mg=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};_.Ng=function(a,b,c,d){Array.prototype.splice.apply(a,Mg(arguments,1))};Og=function(a,b){return null!==a&&b in a?a[b]:void 0};_.Pg=function(){};_.Pg.wc=void 0;_.Pg.i=function(){return _.Pg.wc?_.Pg.wc:_.Pg.wc=new _.Pg};_.Pg.prototype.i=0;_.Qg=function(a){return":"+(a.i++).toString(36)};var Rg;_.Sg=function(a){_.S.call(this);this.o=a||_.Jf();this.X=Rg;this.R=null;this.ya=!1;this.i=null;this.H=void 0;this.F=this.v=this.j=this.B=null;this.va=!1};_.C(_.Sg,_.S);_.Sg.prototype.Ua=_.Pg.i();Rg=null;_.Tg=function(a){return a.R||(a.R=_.Qg(a.Ua))};_.Sg.prototype.D=function(){return this.i};var Ug=function(a,b){if(a==b)throw Error("I");var c;if(c=b&&a.j&&a.R){c=a.j;var d=a.R;c=c.F&&d?Og(c.F,d)||null:null}if(c&&a.j!=b)throw Error("I");a.j=b;_.Sg.V.Ac.call(a,b)};
_.Sg.prototype.Ac=function(a){if(this.j&&this.j!=a)throw Error("J");_.Sg.V.Ac.call(this,a)};_.Sg.prototype.Tb=function(){this.i=_.ie(this.o.i,"DIV")};_.Sg.prototype.render=function(a){Vg(this,a)};var Vg=function(a,b,c){if(a.ya)throw Error("K");a.i||a.Tb();b?b.insertBefore(a.i,c||null):a.o.i.body.appendChild(a.i);a.j&&!a.j.ya||a.Ka()};_.l=_.Sg.prototype;_.l.Uc=function(a){this.i=a};_.l.Ka=function(){this.ya=!0;_.Wg(this,function(a){!a.ya&&a.D()&&a.Ka()})};
_.l.wb=function(){_.Wg(this,function(a){a.ya&&a.wb()});this.H&&_.wg(this.H);this.ya=!1};_.l.N=function(){this.ya&&this.wb();this.H&&(this.H.na(),delete this.H);_.Wg(this,function(a){a.na()});!this.va&&this.i&&_.Gf(this.i);this.j=this.B=this.i=this.F=this.v=null;_.Sg.V.N.call(this)};
_.l.qc=function(a,b,c){if(a.ya&&(c||!this.ya))throw Error("K");if(0>b||b>_.Xg(this))throw Error("M");this.F&&this.v||(this.F={},this.v=[]);if(a.j==this){var d=_.Tg(a);this.F[d]=a;_.Ge(this.v,a)}else{d=this.F;var e=_.Tg(a);if(null!==d&&e in d)throw Error("y`"+e);d[e]=a}Ug(a,this);_.Ng(this.v,b,0,a);a.ya&&this.ya&&a.j==this?(c=this.i,(c.childNodes[b]||null)!=a.D()&&(a.D().parentElement==c&&c.removeChild(a.D()),b=c.childNodes[b]||null,c.insertBefore(a.D(),b))):c?(this.i||this.Tb(),b=_.Yg(this,b+1),Vg(a,
this.i,b?b.i:null)):this.ya&&!a.ya&&a.i&&a.i.parentNode&&1==a.i.parentNode.nodeType&&a.Ka()};_.Xg=function(a){return a.v?a.v.length:0};_.Yg=function(a,b){return a.v?a.v[b]||null:null};_.Wg=function(a,b,c){a.v&&a.v.forEach(b,c)};_.Sg.prototype.Mc=function(a,b){if(a){var c="string"===typeof a?a:_.Tg(a);a=this.F&&c?Og(this.F,c)||null:null;if(c&&a){var d=this.F;c in d&&delete d[c];_.Ge(this.v,a);b&&(a.wb(),a.i&&_.Gf(a.i));Ug(a,null)}}if(!a)throw Error("N");return a};
}catch(e){_._DumpException(e)}
try{
var Zg;Zg=function(a,b,c){if(a.j)return null;if(c instanceof Array){var d=null;for(var e of c)(c=Zg(a,b,e))&&(d=c);return d}d=null;a.i&&a.i.type==c&&a.v==b&&(d=a.i,a.i=null);if(e=b.getAttribute("data-eqid"))b.removeAttribute("data-eqid"),(e=a.B[e])?b.removeEventListener?b.removeEventListener(c,e,!1):b.detachEvent&&b.detachEvent("on"+c,e):a.o.log(Error("x`"+b));return d};_.$g=function(a,b,c){return function(){try{return b.apply(c,arguments)}catch(d){a.log(d)}}};_.bh=function(a,b,c,d,e,f){d=_.$g(a,d,f);a=_.R(b,c,d,e,f);_.ah(b,c);return a};_.ah=function(a,b){if(a instanceof Element&&(b=Zg(_.Fe("eq"),a,b||[])))if(_.D&&b instanceof MouseEvent&&a.dispatchEvent){var c=document.createEvent("MouseEvent");c.initMouseEvent(b.type,!0,!0,b.view,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);a.dispatchEvent(c)}else a.dispatchEvent&&a.dispatchEvent(b)};
}catch(e){_._DumpException(e)}
try{
var fh;_.dh=function(a,b,c){_.ch.listen(b,c,void 0,a.L||a,a)};_.eh=function(a,b){b=b instanceof _.Gc?b:_.Oc(b);a.href=_.Hc(b)};fh=function(a,b,c){var d;a=c||a;if(a.querySelectorAll&&a.querySelector&&b)return a.querySelectorAll(b?"."+b:"");if(b&&a.getElementsByClassName){var e=a.getElementsByClassName(b);return e}e=a.getElementsByTagName("*");if(b){var f={};for(c=d=0;a=e[c];c++){var g=a.className;"function"==typeof g.split&&_.ee(g.split(/\s+/),b)&&(f[d++]=a)}f.length=d;return f}return e};
_.gh=function(a,b){var c=b||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):fh(document,a,b)};_.V=function(a,b){var c=b||document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):fh(c,a,b)[0]||null}return a||null};_.hh=function(a,b){for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null};
_.ih=function(a,b){return b?_.hh(a,function(c){return!b||"string"===typeof c.className&&_.ee(c.className.split(/\s+/),b)}):null};var jh,kh;jh=function(){};_.ch=new jh;kh=["click","keydown","keyup"];jh.prototype.listen=function(a,b,c,d,e){var f=function(g){var h=_.bf(b),k=_.me(g.target)?g.target.getAttribute("role")||null:null;"click"!=g.type||0!=g.Qa.button||_.Eb&&g.ctrlKey?13!=g.keyCode&&3!=g.keyCode||"keyup"==g.type?32!=g.keyCode||"button"!=k&&"tab"!=k&&"radio"!=k||("keyup"==g.type&&h.call(d,g),g.preventDefault()):(g.type="keypress",h.call(d,g)):h.call(d,g)};f.tb=b;f.Eg=d;e?e.listen(a,kh,f,c):_.R(a,kh,f,c)};
jh.prototype.Da=function(a,b,c,d,e){for(var f,g=0;f=kh[g];g++){var h=a;var k=f;var p=!!c;k=_.Re(h)?h.Ad(k,p):h?(h=_.df(h))?h.Ad(k,p):[]:[];for(h=0;p=k[h];h++){var q=p.listener;if(q.tb==b&&q.Eg==d){e?e.Da(a,f,p.listener,c,d):_.hf(a,f,p.listener,c,d);break}}}};var lh;lh=function(a){return Array.isArray(a)?_.bb(a,lh):"string"===typeof a?a:a?a.toString():a};
_.mh=class extends _.sg{constructor(a,b){super(b);this.A=a;this.ua=b||this}listen(a,b,c,d){if(c){if("function"!=typeof c)throw new TypeError("O");c=_.$g(this.A,c,this.ua);c=super.listen(a,b,c,d);_.ah(a,lh(b));return c}return super.listen(a,b,c,d)}s(a,b,c,d,e){if(c){if("function"!=typeof c)throw new TypeError("O");c=_.$g(this.A,c,e||this.ua);c=super.s(a,b,c,d,e);_.ah(a,lh(b));return c}return super.s(a,b,c,d,e)}Ha(a,b,c,d){if(c){if("function"!=typeof c)throw new TypeError("O");c=_.$g(this.A,c,this.ua);
c=super.Ha(a,b,c,d);_.ah(a,lh(b));return c}return super.Ha(a,b,c,d)}};_.nh=class extends _.mh{constructor(a,b){super(b);this.j=a}D(){return this.j}N(){this.j=null;super.N()}};
}catch(e){_._DumpException(e)}
try{
_.oh=class extends _.nh{constructor(a){super(a,_.tc);this.i=_.Pd;(a=_.V("gb_Ec",this.j))&&_.dh(this,a,this.o)}o(a){var b;(a=a.currentTarget)&&(a=a.getAttributeNode("data-ved"))&&a.value&&(b={ved:a.value});this.i.log(39,b)}};
}catch(e){_._DumpException(e)}
try{
_.ph=function(a,b){var c=a.style[_.yg(b)];return"undefined"!==typeof c?c:a.style[_.Dg(a,b)]||""};_.qh=function(a){return void 0!=a.children?a.children:Array.prototype.filter.call(a.childNodes,function(b){return 1==b.nodeType})};_.rh=!_.D&&!_.oa();
}catch(e){_._DumpException(e)}
try{
_.sh=function(a){return null==a?"":String(a)};
}catch(e){_._DumpException(e)}
try{
_.th=function(a){if(a.o)return a.o;for(const b in a.i)if(a.i[b].qa()&&a.i[b].B())return a.i[b];return null};var uh=new class extends _.N{constructor(){var a=_.tc;super();this.B=a;this.o=null;this.j={};this.A={};this.i={};this.s=null}v(a){this.i[a]&&(_.th(this)&&_.th(this).K()==a||this.i[a].P(!0))}Ta(a){this.s=a;for(const b in this.i)this.i[b].qa()&&this.i[b].Ta(a)}tc(a){return a in this.i?this.i[a]:null}};_.pd("dd",uh);
}catch(e){_._DumpException(e)}
try{
var xh,Hh,Ih,Jh,Mh,Ph,Qh,Rh,yh,Sh,Th,Uh,zh,wh,Xh,Yh,Zh,$h,ai,bi,ci,ei,fi,gi,hi,ii,ji,ki,li,mi,ni,oi,pi,qi,ri,si,ti,ui;_.vh=function(a){const b=[];let c=0;for(const d in a)b[c++]=a[d];return b};xh=function(a){return null!=_.hh(a,function(b){return 1==b.nodeType&&"true"==wh(b,"hidden")})};_.Ah=function(a){return a?yh(a,function(b){return 1==b.nodeType&&zh(b)&&!xh(b)}):[]};_.Bh=function(a,b){a&&b&&_.eh(a,a.href.replace(/([?&](continue|followup)=)[^&]*/g,"$1"+encodeURIComponent(b)))};
_.Gh=function(){_.B("gbar.I",_.Ch);_.Ch.prototype.ia=_.Ch.prototype.ka;_.Ch.prototype.ib=_.Ch.prototype.D;_.Ch.prototype.ic=_.Ch.prototype.lb;_.B("gbar.J",_.Dh);_.Dh.prototype.ja=_.Dh.prototype.Y;_.Dh.prototype.jb=_.Dh.prototype.Z;_.B("gbar.K",_.Eh);_.B("gbar.L",_.Fh);_.Fh.prototype.la=_.Fh.prototype.j};Hh=function(a,b){b.xa=b.type;b.xb=b.target;return a.call(this,b)};_.W=function(a,b,c){c?_.Q(a,b):_.ve(a,b)};
Ih=function(a,b,c){a=_.V("gb_Jc",a.D());if(""!=b||""!=c)_.P(a,"gb_Ha")?""!=_.ph(a,"background-image")&&(b=""!=c?c:b,_.T(a,"background-image","url('"+b+"')"),a=_.V("gb_Ic",a),null!==a&&"IMG"==a.tagName&&(a.src=b)):"IMG"==a.tagName&&(a.src=""!=b?b:c,b!=c&&(c=""!=c?c+" 2x ":"",""!=b&&(c=c+(""==c?"":",")+(b+" 1x")),a.setAttribute("srcset",c)))};Jh=function(a,b,c){_.N.call(this);this.tb=a;this.o=b||0;this.i=c;this.j=(0,_.z)(this.Df,this)};_.C(Jh,_.N);_.l=Jh.prototype;_.l.Nc=0;
_.l.N=function(){Jh.V.N.call(this);this.stop();delete this.tb;delete this.i};_.l.start=function(a){this.stop();this.Nc=_.pg(this.j,void 0!==a?a:this.o)};_.l.stop=function(){this.isActive()&&_.qg(this.Nc);this.Nc=0};_.l.isActive=function(){return 0!=this.Nc};_.l.Df=function(){this.Nc=0;this.tb&&this.tb.call(this.i)};_.Kh=function(a,b){b&&_.th(a)&&b!=_.th(a)&&_.th(a).P(!1);a.o=b};_.Lh=function(a,b){a.i[b.K()]=b};Mh=function(a){return String(a).replace(/([A-Z])/g,"-$1").toLowerCase()};
_.Nh=function(a,b){return _.V(a,b)};_.Oh=function(a,b,c){return _.Ff(document,arguments)};Ph=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};Qh=function(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||Qh(a,b,c,d))return!0;a=a.nextSibling}return!1};Rh=function(a,b){var c=[];return Qh(a,b,c,!0)?c[0]:void 0};yh=function(a,b){var c=[];Qh(a,b,c,!1);return c};Sh={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1};Th={IMG:" ",BR:"\n"};
Uh=function(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a};
zh=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!a.hasAttribute("tabindex")||Uh(a)):a.hasAttribute("tabindex")&&Uh(a))&&_.D){var c;"function"!==typeof a.getBoundingClientRect||_.D&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};
_.Vh=function(a,b,c){if(!(a.nodeName in Sh))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Th)b.push(Th[a.nodeName]);else for(a=a.firstChild;a;)_.Vh(a,b,c),a=a.nextSibling};_.Wh=function(a){var b=[];_.Vh(a,b,!0);a=b.join("");a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");a=a.replace(/ +/g," ");" "!=a&&(a=a.replace(/^\s*/,""));return a};
wh=function(a,b){a=a.getAttribute("aria-"+b);return null==a||void 0==a?"":String(a)};Xh=function(a){a.j||(a.j=_.R(a.i,"keydown",a.o,!1,a))};Yh=function(a){a.j&&(_.jf(a.j),a.j=null)};Zh=function(a){Yh(a);_.W(a.i,"gb_I",!1)};$h=class{constructor(a){this.i=a;this.j=null}o(a){9!=a.keyCode||_.P(this.i,"gb_I")||(_.W(this.i,"gb_I",!0),Yh(this))}};
_.Ch=class extends _.S{constructor(a,b){super();this.B=a;b&&(this.B.id=b)}D(){return this.B}ka(){return this.B.id}lb(){let a=this.B.id;a||(a="gb$"+_.Qg(_.Pg.i()),this.B.id=a);return a}N(){_.Gf(this.B);super.N()}};_.Ch.prototype.F=function(){return this.D()};ai=function(a){return Rh(a,function(b){return _.me(b)&&zh(b)})};bi=function(a){(a=ai(a))&&a.focus()};ci={wh:"gb_Ja",Nh:"gb_yd",Vg:"gb_Wc"};
_.di=function(a,b,c){if(_.rh&&a.dataset)a.dataset[b]=c;else{if(/-[a-z]/.test(b))throw Error("A");a.setAttribute("data-"+Mh(b),c)}};ei=function(a){if(/-[a-z]/.test("item"))return null;if(_.rh&&a.dataset){if(_.pa()&&!("item"in a.dataset))return null;a=a.dataset.item;return void 0===a?null:a}return a.getAttribute("data-"+Mh("item"))};fi=function(a,b){return/-[a-z]/.test(b)?!1:_.rh&&a.dataset?b in a.dataset:a.hasAttribute?a.hasAttribute("data-"+Mh(b)):!!a.getAttribute("data-"+Mh(b))};
gi=function(){var a=_.je("LI");_.Q(a,"gb_4c");_.pe(a,"menuitem");return a};hi=class extends _.Ch{constructor(a,b){b||(b=gi(),a.F().appendChild(b));super(b);this.C=new _.sg(this);_.dh(this.C,this.D(),this.K)}G(a){a?_.di(this.D(),"item",a):(a=this.D(),!/-[a-z]/.test("item")&&(_.rh&&a.dataset?fi(a,"item")&&delete a.dataset.item:a.removeAttribute("data-"+Mh("item"))));return this}j(){return ei(this.D())}H(a){_.W(this.D(),"gb_Ra",a);return this}focus(){bi(this.D())}K(){this.dispatchEvent("click")}};
ii=class extends hi{constructor(a,b){if(!b){b=gi();_.Q(b,"gb_9c");var c=_.Oh("A","gb_6c");c.tabIndex=0;b.appendChild(c);var d=_.Oh("SPAN","gb_7c");c.appendChild(d);a.F().appendChild(b)}super(a,b);this.v=_.Nh("gb_6c",this.D());this.s=_.V("gb_8c",this.v);this.i=null;this.o=_.V("gb_7c",this.v)}j(){return super.j()||this.A()}A(){return _.Wh(this.o)}J(a){_.ne(this.o,a);return this}M(a){if(!this.s)if(this.s=_.Oh("IMG","gb_8c"),this.s.setAttribute("alt",""),this.i)Ph(this.s,this.i),this.i=null;else{var b=
this.o;b.parentNode&&b.parentNode.insertBefore(this.s,b)}this.s.setAttribute("src",a);return this}L(a){if(!(a instanceof Element&&"svg"==a.tagName.toLowerCase()))return this;if(this.s)Ph(a,this.s),this.s=null;else if(this.i)Ph(a,this.i);else{var b=this.o;b.parentNode&&b.parentNode.insertBefore(a,b)}(b=a.getAttribute("class"))?a.setAttribute("class",b+" gb_8c"):a.setAttribute("class","gb_8c");this.i=a;return this}focus(){this.v.focus()}};
_.Dh=class extends _.Ch{constructor(a){super(a);this.A=[];this.K={}}Y(a){let b=this.K[a];if(b)return b;const c=document.getElementById(a);if(c)for(let d=0,e=this.A.length;d<e;++d)if(b=this.A[d],b.D()==c)return this.K[a]=b;return null}s(a){a.Ac(this);this.A.push(a);const b=a.B.id;b&&(this.K[b]=a)}Z(){for(let a=0,b=this.A.length;a<b;a++)this.A[a].na();this.K={};this.A=[]}};
ji=class extends _.Dh{constructor(a,b){if(!b){b=_.je("UL");_.Q(b,"gb_1c");var c=_.Oh("SPAN","gb_5c");b.appendChild(c)}super(b);this.j=a;a=this.D().getElementsByClassName("gb_4c");for(b=0;b<a.length;b++)c=a[b],_.P(c,"gb_9c")?this.s(new ii(this,c)):this.s(new hi(this,c));this.i=_.V("gb_5c",this.D())}s(a){super.s(a);var b=this.j,c=a.D();c=c.id||(c.id="gbm"+_.Qg(_.Pg.i()));b.O[c]=a}o(){return null!=this.i?_.Wh(this.i):null}v(a){return null!=this.i?(_.ne(this.i,a),this):null}C(){var a=new hi(this);this.s(a);
return a}G(){var a=new ii(this);this.s(a);return a}};ki=function(a){return a instanceof HTMLElement&&fi(a,"ogobm")};li="click mousedown scroll touchstart wheel keydown".split(" ");mi=class{constructor(a,b){this.i=a;this.j=b}};
ni=function(a){_.dh(a.j,a.D(),a.ua);a.D().addEventListener("keydown",function(c){32==c.keyCode&&c.preventDefault()});_.dh(a.j,a.o,a.nb);a.j.listen(a.i,"keydown",a.va);a.j.listen(a.i,"keyup",a.mb);const b=new Map;b.set("close","cbc");b.set("back","bbc");b.forEach((c,d)=>{_.dh(a.j,a.J.get(d),function(){this.dispatchEvent(c)})});if(_.P(a.i,"gb_Ja")||_.P(a.i,"gb_yd"))a.j.listen(window,"resize",a.U),a.U();_.P(a.i,"gb_Rc")||a.j.Ha(window,"touchstart",()=>{_.T(a.i,"overflow-y","auto")})};
oi=function(a){a.j.Da(document.body,li,a.S,!1,a);a.j.Da(document.body,"focusin",a.R)};pi=function(a){a.C||(a.C=_.je("DIV"),_.Q(a.C,"gb_Zc"),a.o.appendChild(a.C),a.H=_.je("DIV"),_.Q(a.H,"gb_0c"),a.o.appendChild(a.H))};qi=function(a,b){const c=new ji(a);var d=c.D();b.appendChild(d);a.s(c);return c};ri=function(a,b){(a=a.J.get(b))&&_.ve(a,"gb_j")};si=function(a){a.J.forEach(b=>{_.Q(b,"gb_j")})};ti=function(a){return!_.P(a.i,"gb_Vc")||_.P(a.i,"gb_Ja")||_.P(a.i,"gb_yd")};
ui=class extends _.Dh{constructor(a,b,c,d,e){const f=a.get("menu");super(f);this.i=b;this.X=f;this.J=a;this.ma=a.get("back");this.G=_.V("gb_Mc");this.L=c;this.o=_.V("gb_Xc",this.i);this.M=new $h(this.o);this.C=_.V("gb_Zc",this.o);this.H=_.V("gb_0c",this.o);this.O={};this.P=[];this.T=d||!1;this.W=e||!1;this.j=new _.sg(this);ni(this);a=this.o.getElementsByClassName("gb_1c");for(b=0;b<a.length;b++)this.s(new ji(this,a[b]))}N(){super.N();oi(this)}F(){return this.o}qa(){return _.V("gb_3d",this.i)}Ua(){pi(this);
return qi(this,this.C)}Na(){pi(this);return qi(this,this.H)}Ba(a){_.W(this.i,"gb_Vc",1==a);this.dispatchEvent("msc")}getStyle(){return ti(this)?0:1}Xa(a){this.G||(this.G=_.V("gb_Mc"));this.G&&a&&_.ne(this.G,a)}isVisible(a){return(a=this.J.get(a))?!_.P(a,"gb_j"):!1}open(a){this.L||(a&&_.T(this.i,"transition","none"),this.dispatchEvent("beforeshow"),_.Q(this.i,"gb_Da"),_.qe(this.D(),"expanded",!0),bi(this.o),Xh(this.M),this.dispatchEvent("open"),this.j.s(document.body,li,this.S,!0,this),this.j.listen(document.body,
"focusin",this.R),a&&_.pg(function(){_.T(this.i,"transition","")},0,this))}Wa(a){this.L&&_.qe(this.D(),"expanded",a)}close(a){this.L||(a&&_.T(this.i,"transition","none"),_.ve(this.i,"gb_Da"),_.qe(this.D(),"expanded",!1),document.activeElement==this.D()&&this.D().blur(),Zh(this.M),this.dispatchEvent("close"),oi(this),a&&_.pg(function(){_.T(this.i,"transition","")},0,this))}v(){return _.P(this.i,"gb_Da")}U(){const a=window.visualViewport?window.visualViewport.height:window.innerHeight;a&&_.T(this.i,
"height",`calc(${a}px - 100%)`)}ua(){this.dispatchEvent("mbc");if(!this.L){if(this.v()){this.close();var a=!0}else this.open(),a=!1;a&&this.D().focus()}}mb(a){9===a.keyCode&&this.v()&&(a=this.M,_.W(a.i,"gb_I",!0),Yh(a))}va(a){a:{if(36==a.keyCode||35==a.keyCode){var b=_.Ah(this.i);if(0<b.length){var c=b[b.length-1];36==a.keyCode&&(c=!ti(this)&&1<b.length?b[1]:b[0]);c.focus();a.preventDefault();break a}}27!=a.keyCode||this.T&&!ti(this)||(this.close(),null!=this.X&&this.X.focus())}9===a.keyCode&&this.v()&&
ti(this)&&(b=a.target,c=_.Ah(this.i),0<c.length&&(b==c[0]&&a.shiftKey?(c[c.length-1].focus(),a.preventDefault()):b!=c[c.length-1]||a.shiftKey||(c[0].focus(),a.preventDefault())))}nb(a){if(a.target instanceof Node){a:{a=a.target;for(var b=this.o;a&&a!==b;){var c=a.id;if(c in this.O){a=this.O[c];break a}a=a.parentNode}a=null}if(a){b=a.j();c=this.P.length;for(let d=0;d<c;++d)a=this.P[d],a.i.call(a.j,b);this.T&&!ti(this)||this.close()}}}S(a){this.v()&&a.target instanceof Node&&!(!ti(this)||this.W&&_.hh(a.target,
ki))&&("keydown"==a.type?27==a.keyCode&&(a.preventDefault(),a.stopPropagation(),this.close(),this.D().focus()):_.ih(a.target,"gb_S")||_.ih(a.target,"gb_Kc")||_.Hf(this.i,a.target)||("touchstart"==a.type&&(a.preventDefault(),a.stopPropagation()),this.close()))}R(){this.v()&&(!ti(this)||"IFRAME"!=document.activeElement.tagName&&(this.W&&_.hh(document.activeElement,ki)||_.ih(document.activeElement,"gb_Qc")||_.ih(document.activeElement,"gb_S")||bi(this.o)))}Ca(a,b){this.P.push(new mi(a,b))}};
_.Eh=class extends _.Ch{constructor(a){super(a);_.ch.listen(a,this.i,!1,this)}i(a){this.dispatchEvent("click")||a.preventDefault()}};var vi=class{constructor(){this.i=null}Xc(){return this.i}};var wi=class{constructor(a,b,c){this.i=a;this.j=b;this.o=c||_.m}};var xi=class{constructor(a){this.i=[];this.s=a||this}j(a,b,c){this.v(a,b,c);this.i.push(new wi(a,b,c))}v(a,b,c){c=c||_.m;for(var d=0,e=this.i.length;d<e;d++){var f=this.i[d];if(f.i==a&&f.j==b&&f.o==c){this.i.splice(d,1);break}}}o(a){a.i=this.s;for(var b=0,c=this.i.length;b<c;b++){var d=this.i[b];"catc"==d.i&&d.j.call(d.o,a)}}};var zi=function(a,b){_.S.call(this);this.i=a;this.o=yi(this.i);this.A=b||100;this.s=_.R(a,"resize",this.v,!1,this)};_.C(zi,_.S);zi.prototype.N=function(){_.jf(this.s);zi.V.N.call(this)};zi.prototype.v=function(){this.j||(this.j=new Jh(this.B,this.A,this),_.qf(this,this.j));this.j.start()};
zi.prototype.B=function(){if(!this.i.isDisposed()){var a=this.o,b=yi(this.i);this.o=b;if(a){var c=!1;a.width!=b.width&&(this.dispatchEvent("b"),c=!0);a.height!=b.height&&(this.dispatchEvent("a"),c=!0);c&&this.dispatchEvent("resize")}else this.dispatchEvent("a"),this.dispatchEvent("b"),this.dispatchEvent("resize")}};var Ai=function(a){_.S.call(this);this.j=a||window;this.o=_.R(this.j,"resize",this.s,!1,this);this.i=_.Cf(this.j||window)};_.C(Ai,_.S);var Ci=function(){var a=window,b=_.Ee(a);return Bi[b]=Bi[b]||new Ai(a)},Bi={},yi=function(a){return a.i?_.xg(a.i):null};Ai.prototype.N=function(){Ai.V.N.call(this);this.o&&(_.jf(this.o),this.o=null);this.i=this.j=null};Ai.prototype.s=function(){var a=_.Cf(this.j||window);_.Ag(a,this.i)||(this.i=a,this.dispatchEvent("resize"))};var Di=function(a,b){for(var c=0,d=b.length-1,e=b[0];c<d;){if(a<=e.max)return e.id;e=b[++c]}return b[d].id},Ei=class{constructor(a,b){this.s=new xi(this);this.C=a;this.B=b;this.i=Di(a.offsetWidth,this.B);this.F=new zi(Ci(),10);_.R(this.F,"b",function(){window.requestAnimationFrame?window.requestAnimationFrame((0,_.z)(this.A,this)):this.A()},!1,this)}A(){var a=Di(this.C.offsetWidth,this.B);a!=this.i&&(this.i=a,this.o(new vi))}j(a,b,c){this.s.j(a,b,c)}v(a,b){this.s.v(a,b)}o(a){this.s.o(a)}};_.Fh=class extends _.Ch{constructor(a){super(a);_.R(a,"click",this.i,!1,this)}j(){var a=this.D().getAttribute("aria-pressed");return(null==a?a:"boolean"===typeof a?a:"true"==a)||!1}i(a){a=a.currentTarget;var b=wh(a,"pressed");_.tf(_.sh(b))||"true"==b||"false"==b?_.qe(a,"pressed","true"==b?"false":"true"):a.removeAttribute("aria-pressed");this.dispatchEvent("click")}};var Fi,Gi,Hi,Ii,Ri,Oi,Si,Ti,Pi,Ji,Ki,Li,Ni,Qi,Vi,Xi,Wi,Yi,X,aj,Zi,$i;Fi=function(a,b){if(a=_.V(b?"gb_9d":"gb_ae",a.o)){var c=a.offsetWidth;_.xb(a.children,function(d){_.P(d,"gb_j")&&(c-=d.offsetWidth)});return c}return 0};Gi=function(a,b){null==a.B?a.M.log(Error("W")):a.ka?a.M.log(Error("X")):a.Xa=0>b?0:b};Hi=function(a,b,c){var d=320,e=_.hb(_.gc(a.j,29),0);0<e&&(d=e);e=d+2*Math.max(b,c);b=d+b+c;return e!=b&&a.ka?[{id:1,max:b},{id:2,max:e},{id:3}]:[{id:1,max:b},{id:3}]};
Ii=function(a){var b=_.O.i();a.v||_.Be(b.i,Error("R"));_.x(_.F(a.j,7))||_.Be(b.A,Error("S"));_.x(_.F(a.j,12))||_.Be(b.v,Error("T"));_.x(_.F(a.j,13))||_.Be(b.B,Error("U"))};
Ri=function(a,b){!a.i&&a.v&&Ji(a);a.i&&!a.P&&a.J("default");a.i&&a.jc&&a.J("none");Ki(a);if(a.kc)a.K=!0;else if(a.lc)a.K=!1;else if(a.Y)a.K=!0;else if(a.X)a.K=!1;else{var c=_.x(_.F(a.j,5),!1),d=_.x(_.F(a.j,7),!1);a.K=!("gb_Ja"===b&&(c||d))}c="gb_Ja"==b;d="gb_yd"==b;a.hc&&a.U&&_.W(a.U,"gb_j",c||d);var e=Li(a,b);a.i&&e?_.Mi(a)||null==a.S||(e=_.V("gb_2c"),a.S.parentNode!=e&&e.insertBefore(a.S,e.childNodes[0]||null),_.Q(a.A,"gb_Fd"),a.qa(),a.dispatchEvent("upi")):_.Mi(a)&&a.v&&null!=a.S&&(e=a.me,e.insertBefore(a.S,
e.childNodes[0]||null),_.ve(a.A,"gb_Fd"),a.qa(),a.dispatchEvent("upo"));_.G(a.j,44)&&!a.Y&&!_.G(a.j,10)&&1<Ni(a).length&&a.U&&a.A&&(_.W(a.U,"gb_j",c),_.W(a.A,"gb_Fd",c));if(a.F&&!a.Y){e=a.F.D();var f=!a.X;_.W(e,"gb_j",!f);f&&Oi(a,a.K)}a.i&&(a.i.isVisible("menu")||a.i.isVisible("back"))&&!ti(a.i)&&(a.mb=a.i.v());e=_.vh(ci);_.we(a.o,e);_.Q(a.o,b);if(a.ka&&null!=a.C)if("gb_Wc"!=b)_.T(a.C,"min-width",""),_.T(a.A,"min-width","");else{f=_.Jg(a.C).width;var g=_.Jg(a.A).width;f=Math.max(f,g);_.T(a.C,"min-width",
f+"px");_.T(a.A,"min-width",f+"px")}c?a.T||(a.T=!0,Pi(a,a.T)):(a.T=!1,a.Ba());null!=a.B&&(_.W(a.B,"gb_te",!c&&!d),_.W(a.B,"gb_se",c||d));a.i&&(c=a.i.i,_.we(c,e),_.Q(c,b),ti(a.i)?_.V("gb_Od").appendChild(c):a.o.appendChild(c),a.i.isVisible("menu")||a.i.isVisible("back"))&&(b=!ti(a.i),c=a.i.v(),b&&!c&&a.mb?a.i.open():!b&&c&&a.i.close());Qi(a)};Oi=function(a,b){var c=_.V("gb_Jc",a.F.D());_.W(c,"gb_j",!b);a=_.V("gb_Md",a.F.D());null!=a&&_.W(a,"gb_2d",!b)};
Si=function(a){a=a.Z[0];return a.classList.contains("gb_Lc")?1:a.classList.contains("gb_Ld")?2:0};Ti=function(a,b){if(a.F){if(2==b){b=_.y(_.E(a.j,24),"");var c=_.y(_.E(a.j,27),"")}else 1==b?(b=_.y(_.E(a.j,23),""),c=_.y(_.E(a.j,26),"")):(b=_.y(_.E(a.j,22),""),c=_.y(_.E(a.j,25),""));""==b&&""==c||Ih(a.F,b,c)}};_.Ui=function(a,b,c){a.i&&(ti(a.i)&&(c=b=!1),a=document.body,_.W(a,"gb_7d",b),_.W(a,"gb_6d",c))};
Pi=function(a,b){if(_.G(a.j,7)&&(!a.T||b)){if(a.ka){var c=_.V("gb_9d",a.o);if(c){var d=_.V("gb_ae",a.o),e="gb_Wc"!=a.H.i||b?"":a.oc+"px";_.T(c,"min-width",e);_.T(d,"min-width",e)}}_.P(a.B,"gb_ne")!=b&&(_.W(a.B,"gb_ne",b),b?a.dispatchEvent("sfi"):a.dispatchEvent("sfu"),_.W(_.V("gb_Be",a.B),"gb_ne",b),b&&a.va())}};
Ji=function(a){var b=_.V("gb_Qc");if(b){var c=new Map;c.set("menu",_.V("gb_Kc",a.o));c.set("back",_.V("gb_Nc"));c.set("close",_.V("gb_Oc"));var d=!1;c.forEach(e=>{e||(a.M.log(Error("P")),d=!0)});if(!d){a.i=new ui(c,b,_.x(_.F(a.j,16),!1),_.x(_.F(a.j,9),!1),_.x(_.F(a.j,33),!1));a.i.listen("open",a.Zb,!1,a);a.i.listen("close",a.Yb,!1,a);a.i.listen("msc",a.bc,!1,a);switch(_.E(a.j,32)){case 1:a.J("back");break;case 2:a.J("close");break;case 3:a.J("none");break;default:a.J("default")}_.Gh();_.B("gbar.C",
ui);ui.prototype.ca=ui.prototype.F;ui.prototype.cb=ui.prototype.Ua;ui.prototype.cc=ui.prototype.Ca;ui.prototype.cd=ui.prototype.Ba;ui.prototype.ce=ui.prototype.Na;ui.prototype.cf=ui.prototype.open;ui.prototype.cg=ui.prototype.close;ui.prototype.ch=ui.prototype.getStyle;ui.prototype.ck=ui.prototype.v;ui.prototype.cl=ui.prototype.Wa;ui.prototype.cm=ui.prototype.qa;ui.prototype.cn=ui.prototype.Xa;_.B("gbar.D",ji);ji.prototype.da=ji.prototype.C;ji.prototype.db=ji.prototype.G;ji.prototype.dc=ji.prototype.o;
ji.prototype.dd=ji.prototype.v;_.B("gbar.E",hi);hi.prototype.ea=hi.prototype.D;hi.prototype.eb=hi.prototype.H;hi.prototype.ec=hi.prototype.G;hi.prototype.ed=hi.prototype.j;_.B("gbar.F",ii);ii.prototype.fa=ii.prototype.J;ii.prototype.fb=ii.prototype.M;ii.prototype.fc=ii.prototype.L;ii.prototype.fd=ii.prototype.A;ii.prototype.ed=ii.prototype.j;_.O.i().i.resolve(a.i)}}else a.M.log(Error("Q"))};Ki=function(a){null!=a.C&&("gb_Ja"==a.H.i?_.T(a.C,"min-width",""):null!=a.Xa&&_.T(a.C,"min-width",a.Xa+"px"))};
Li=function(a,b){var c=_.x(_.F(a.j,5),!1),d=_.x(_.F(a.j,2),!1);return!(_.x(_.F(a.j,10),!1)||a.Y||_.x(_.F(a.j,44),!1))&&d&&("gb_Ja"==b||"gb_yd"==b&&(c||a.X))};Ni=function(a){var b=_.V("gb_9d",a.o),c=_.V("gb_ae",a.o),d=[];b&&_.xb(b.children,function(e){d.push(e)});_.x(_.F(a.j,7),!1)&&(a=_.V("gb_ne",a.B))&&(a=_.V("gb_5e",a),a.i=!0,d.push(a));c&&_.xb(c.children,function(e){d.push(e)});return d};Qi=function(a){var b=a.o.offsetHeight+"px";a.nb!=b&&(a.nb=b,a.vb&&(a.vb.style.height=b),a.dispatchEvent("resize"))};
Vi=function(a){return function(){a.click()}};Xi=function(a,b,c){b=_.rg(b,function(f){return _.P(f,"gb_ce")?(Wi(this,f),!1):!0},a);for(var d=0;d<b.length;d++){var e=b[d];d>=c?Wi(a,e):_.ve(e,"gb_j")}};
Wi=function(a,b){_.Q(b,"gb_j");var c=_.je("LI");_.ue(c,["gb_je","gb_4c","gb_9c"]);c.tabIndex=0;_.dh(a.O,c,Vi(b));var d=_.Oh("A","gb_6c");c.appendChild(d);var e=_.Oh("SPAN","gb_7c");d.appendChild(e);d=b.i?b.getAttribute("aria-label"):b.title;_.ne(e,d);d=!1;_.P(b,"gb_ef")&&(d=!0);var f,g=b.children[0];d?f=g.children[0].children[0].src:b.i?f="https://www.gstatic.com/images/icons/material/system/1x/search_black_24dp.png":f=g.src;a.s=_.Oh("IMG");_.ue(a.s,["gb_8c","gb_ke"]);a.s.setAttribute("src",f);e.parentNode&&
e.parentNode.insertBefore(a.s,e);a.R.appendChild(c)};_.Mi=function(a){return!!a.i&&_.P(a.A,"gb_Fd")};Yi=function(a,b){_.we(a,["gb_Ld","gb_Lc"]);1==b?_.Q(a,"gb_Lc"):2==b&&_.Q(a,"gb_Ld")};
X=class extends _.S{constructor(a,b,c,d){super();this.o=a;_.ve(this.o,"gb_sd");this.j=b;this.M=c;this.nb="";this.vb=d;this.F=this.i=null;this.mb=this.P=this.K=!1;this.Y=_.x(_.F(this.j,16),!1);this.O=new _.sg(this);this.Na=_.V("gb_ad",this.o);this.U=_.V("gb_Q",this.o);this.X=_.x(_.F(b,6),!1);this.Qc=_.V("gb_ed",this.Na);this.v=_.V("gb_ud",this.o);this.L=_.V("gb_Bd",this.o);(this.ua=_.x(_.F(this.j,21),!1))&&this.v&&(this.Ca=_.V("gb_he",this.o),this.md=_.V("gb_le",this.o),this.R=_.V("gb_ie",this.o));
this.A=_.V("gb_Ed",this.o);this.S=_.V("gb_3c",this.o);this.me=_.V("gb_Ae",this.o);this.C=_.V("gb_cd",this.o);this.B=_.V("gb_Dd",this.o);this.Z=Array.prototype.slice.call(_.gh("gb_Kd",this.o));this.T=!1;this.kc=_.x(_.F(this.j,19),!1);this.jc=_.x(_.F(this.j,20),!1);this.hc=_.x(_.F(this.j,45),!1);this.lc=_.x(_.F(this.j,46),!1);a=Fi(this,!0);b=Fi(this,!1);this.oc=Math.max(a,b);this.ka=_.F(this.j,15);c=_.hb(_.gc(this.j,30),0);0!=c&&Gi(this,c);a=Hi(this,a,b);this.H=new Ei(this.o,Zi);this.Nb=_.y(_.E(this.j,
37));this.Mb=_.y(_.E(this.j,38));_.P(this.o,"gb_n");this.Tc=_.x(_.F(this.j,39));this.ua&&this.v&&(this.Wa=new Ei(this.o,$i),this.Wa.j("catc",this.va,this),this.va(),_.dh(this.O,this.Ca,function(){var e=this.md,f=!_.P(e,"gb_j");_.W(e,"gb_j",f)}));this.nc=_.x(_.F(this.j,1),!1);this.mc=_.x(_.F(this.j,40),!1);Ii(this);Ri(this,this.H.i);this.H.j("catc",this.Xb,this);_.G(this.j,8)&&document.addEventListener("scroll",(0,_.z)(function(){_.W(this.o,"gb_wd",0<window.scrollY)},this));null!=this.B&&_.G(this.j,
7)&&(this.ma=new Ei(this.B,a),this.ma.j("catc",this.Ba,this),this.Ba());this.G=null;if(this.W=_.V("gb_Ba",this.o))this.G=_.V("gb_Ha",this.W),this.O.s(this.G,"error",this.Wb,!1,this)}Wb(){null!=this.G&&(this.G.src="https://www.gstatic.com/images/icons/material/system/1x/broken_image_grey600_18dp.png",this.G.srcset="https://www.gstatic.com/images/icons/material/system/1x/broken_image_grey600_18dp.png 1x, https://www.gstatic.com/images/icons/material/system/2x/broken_image_grey600_18dp.png 2x",_.T(this.G,
"width","auto"),_.Q(this.G.parentElement,"gb_Fa"),_.T(this.G.parentElement,"line-height","30px"))}D(){return this.o}jd(a){this.F=a;Oi(this,this.K);a=Si(this);0!=a&&Ti(this,a)}kd(a,b){this.F&&Ih(this.F,a,b)}Ta(a){this.ub(a||this.Tc?1:0);this.Ua(a?this.Nb:this.Mb);_.W(this.D(),"gb_g",a);const b=_.V("gb_Qd");null!=b&&_.W(b,"gb_g",a);this.i&&this.mc&&_.W(this.i.i,"gb_Uc",a);this.W&&_.W(this.W,"gb_g",a);_.Fe("dd").Ta(a)}ke(a){this.Na&&(_.ne(this.Qc,a||""),_.W(this.Na,"gb_j",!a),this.X=!!a,Ri(this,this.H.i))}Lb(){return _.V("gb_3d",
this.v)}Ba(){if(null!=this.ma){var a=this.ma.i;3==a?Pi(this,!1):1==a?Pi(this,!0):Pi(this,"gb_Wc"==this.H.i)}}va(){if(this.ua&&this.v){var a=Ni(this),b=!1;a=_.rg(a,function(f){b=b||_.P(f,"gb_ce");return _.P(f,"gb_id")||_.P(f,"gb_ef")||_.P(f,"gb_5e")});var c=this.Wa.i.Hd,d=!1;if(a.length>c||b)d=!0,c--;var e=a.length-c;if(d!=!_.P(this.Ca,"gb_j")||e!=this.R.children){_.W(this.Ca,"gb_j",!d);if(d)for(;this.R.firstChild;)this.R.removeChild(this.R.firstChild);Xi(this,a,c);d?this.O.s(document.body,aj,this.lb,
!0,this):this.O.Da(document.body,aj,this.lb,!1,this)}}}lb(a){!_.P(this.md,"gb_j")&&a.target instanceof Node&&("keydown"==a.type?27==a.keyCode&&(a.preventDefault(),a.stopPropagation(),_.Q(this.md,"gb_j"),this.D().focus()):_.Hf(this.md,a.target)||("touchstart"==a.type&&(a.preventDefault(),a.stopPropagation()),_.Q(this.md,"gb_j")))}Xb(){Ri(this,this.H.i);this.i&&_.Ui(this,this.i.v(),!1);this.dispatchEvent("ffc")}Zb(){_.Ui(this,!0,!0)}Yb(){_.Ui(this,!1,!0)}bc(){var a=ti(this.i),b=this.i.i;a?_.V("gb_Od").appendChild(b):
this.o.appendChild(b)}J(a){var b=!1;switch(a){case "back":this.P=!0;si(this.i);ri(this.i,"back");b=!0;break;case "close":this.P=!0;si(this.i);ri(this.i,"close");b=!0;break;case "default":this.P=!1;Li(this,this.H.i)||this.nc?(this.i&&!this.i.isVisible("menu")&&(si(this.i),ri(this.i,"menu")),b=!0):(this.i&&this.i.isVisible("back")&&si(this.i),this.i&&this.i.isVisible("menu")?(a=this.i,a.close(),_.Q(a.D(),"gb_j"),!_.P(a.ma,"gb_j")&&_.ve(a.D(),"gb_Pc")):(a=_.V("gb_Kc",this.o))&&_.Q(a,"gb_j"),b=!1);break;
case "none":this.P=!0,si(this.i),b=!1}null!=this.C&&_.W(this.C,"gb_dd",b)}Kb(){return this.o.offsetHeight}Pc(){this.L&&Qi(this)}Vb(){if(!this.L){var a=_.je("DIV");_.ue(a,["gb_Bd","gb_Kd"]);Yi(a,Si(this));a.style.backgroundColor=this.o.style.backgroundColor;this.Z.push(a);var b=this.v;b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling);this.L=a}return this.L}Rc(){_.Gf(this.L);this.L=null;Qi(this)}ub(a){2==a&&(a=0);for(var b=0;b<this.Z.length;b++)Yi(this.Z[b],a);Ti(this,a)}Ua(a){this.o.style.backgroundColor=
a}Db(){return this.o.style.backgroundColor}qa(){var a=_.Fe("dd");_.th(a)&&_.th(a).P(!1);_.Kh(a,null)}Zc(a){Gi(this,a-8-10);Ki(this)}ie(a){_.W(_.V("gb_Cc",this.v),"gb_j",!a)}Sc(a){a&&(_.Bh(_.V("gb_Qd"),a),_.O.i().j.then(b=>void b.Kd(a)))}};aj="click mousedown scroll touchstart wheel keydown".split(" ");Zi=[{id:"gb_Ja",max:599},{id:"gb_yd",max:1023},{id:"gb_Wc"}];
$i=[{id:{id:"oneProductControl",Hd:1},max:320},{id:{id:"twoProductControl",Hd:2},max:360},{id:{id:"threeProductControl",Hd:3},max:410},{id:{id:"unlimitedProductControl",Hd:Number.MAX_SAFE_INTEGER}}];var bj;_.S.prototype.za=_.fe(function(a,b,c,d,e){return a.call(this,b,_.fe(Hh,c),d,e)},_.S.prototype.listen);_.S.prototype.zb=_.S.prototype.fg;var cj=_.V("gb_Ia");
if(null==cj)bj=null;else{var dj=_.H(_.Kd,_.Ce,6)||new _.Ce,ej=new X(cj,dj,_.tc,_.V("gb_xd"));_.B("gbar.P",X);X.prototype.pa=X.prototype.Kb;X.prototype.pb=X.prototype.ke;X.prototype.pc=X.prototype.ub;X.prototype.pd=X.prototype.Ua;X.prototype.pe=X.prototype.Vb;X.prototype.pf=X.prototype.Pc;X.prototype.pg=X.prototype.Rc;X.prototype.ph=X.prototype.Lb;X.prototype.pi=X.prototype.qa;X.prototype.pj=X.prototype.Zc;X.prototype.pk=X.prototype.ie;X.prototype.pl=X.prototype.Sc;X.prototype.pm=X.prototype.J;X.prototype.pn=
X.prototype.Db;X.prototype.po=X.prototype.kd;X.prototype.pp=X.prototype.Ta;_.O.i().s.resolve(ej);bj=ej}_.Y=bj;
}catch(e){_._DumpException(e)}
try{
var fj=document.querySelector(".gb_b .gb_e"),gj=document.querySelector("#gb.gb_Tc");fj&&!gj&&_.ae(_.Qd,fj,"click");
}catch(e){_._DumpException(e)}
try{
(function(){for(var a=document.querySelectorAll(".gb_Ec"),b=0;b<a.length;b++)_.ae(_.Qd,a[b],"click");_.O.i().s.then(function(c){if(c){var d=_.V("gb_Cc",c.v);d&&(d=new _.oh(d),c.jd(d))}})})();
}catch(e){_._DumpException(e)}
})(this.gbar_);
// Google Inc.
